apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-dev-reviews
  namespace: student14-bookinfo-dev
  labels:
    app: bookinfo-dev-reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo-dev-reviews
  template:
    metadata:
      labels:
        app: bookinfo-dev-reviews
    spec:
      containers:
      - name: bookinfo-dev-reviews
        image: ghcr.io/supakkavee/bookinfo-reviews:dev
        imagePullPolicy: Always
        env:
        - name: SERVICE_VERSION
          value: v1
        - name: ENABLE_RATINGS
          value: "true"
        - name: RATINGS_SERVICE
          value: http://bookinfo-dev-ratings:8080
      imagePullSecrets:
      - name: registry-bookinfo
